name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    RUSTFLAGS: -Dwarnings
    AWS_KMS_TEST_KEY_ARN: arn:aws:kms:us-east-1:667861386598:key/d7da2f8d-2bdf-4c62-963f-16c921522fee
    AWS_KMS_TEST_ROLE_ARN: arn:aws:iam::667861386598:role/aws-nitro-enclaves-cose-tests
    TEST_KEY_SIG_ALG: ES384

jobs:
    test:
        name: Test on rust ${{matrix.rust}}  (keys ${{ matrix.key_feature_set }})
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        strategy:
            matrix:
                rust: [1.58.1, stable, nightly]
                key_feature_set:
                  - key_openssl_pkey
                  - key_kms
        steps:
        - uses: actions/checkout@v3
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ env.AWS_KMS_TEST_ROLE_ARN }}
            aws-region: us-east-1
        - uses: dtolnay/rust-toolchain@master
          with:
              toolchain: ${{matrix.rust}}
        - run: cargo test --all --no-default-features --features ${{ matrix.key_feature_set }}

    test_fedora:
        name: Test on Fedora
        runs-on: ubuntu-latest
        container: fedora:latest
        steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: |
              dnf install -y \
                  tpm2-tss-devel \
                  swtpm swtpm-tools \
                  rust cargo clippy
        - name: Start swtpm
          run: |
              mkdir /tmp/tpmdir
              swtpm_setup --tpm2 \
                  --tpmstate /tmp/tpmdir \
                  --createek --decryption --create-ek-cert \
                  --create-platform-cert \
                  --display
              swtpm socket --tpm2 \
                  --tpmstate dir=/tmp/tpmdir \
                  --flags startup-clear \
                  --ctrl type=tcp,port=2322 \
                  --server type=tcp,port=2321 \
                  --daemon
        - name: Run tests
          run: |
              TCTI=swtpm: cargo test --features key_tpm,key_openssl_pkey
        - name: Run clippy
          run: |
              cargo clippy --features key_tpm,key_openssl_pkey --all

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: dtolnay/rust-toolchain@stable
        - run: rustup component add clippy
        - run: cargo clippy --all

    fmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: dtolnay/rust-toolchain@stable
        - run: rustup component add rustfmt
        - run: cargo fmt --all -- --check
